---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Stránky
- type: document
  path: _pages/cs/index.md
  label: Úvodní stránka (česky)
- type: document
  path: _pages/en/index.md
  label: Home Page (English)
- type: jekyll-pages
  label: Nějaké stránky
  create: documents
  new_doc_ext: md
  templates:
  - landing-page
- type: heading
  label: Denní menu
- type: directory
  path: _daily_menus/cs
  label: Denní menu (česky)
  create: documents
  match: "**/*.yml"
  new_doc_ext: yml
  templates:
  - daily-menu
- type: heading
  label: Nastavení
- type: document
  path: _data/contacts.yml
  label: Kontakty
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
